### ISSUE TITLE
improper character appears on the edge when game in the reverse mode

### ISSUE THREAD

**Issue by pkali** [Pecusx/dino-game#1]
Reported by @peterdell https://github.com/peterdell

> I found a glitch in the scroller in the right to left mode. When the cactus just scrolled out of the visible area, a $2d character appears in the left character of the last line.

![cfa6a072-315d-4632-b1e3-44d5c6c44232](https://github.com/user-attachments/assets/d4472cfa-46a7-47c9-862f-8bdb8bb61d4a)

**Comment by Pecusx** [comment]
Fixed: https://github.com/Pecusx/dino-game/commit/5d39d86ea1baa215e34b727b0c5e2877bb36761d
